openapi: 3.0.0
info:
  title: bal existing
  version: 1.0.0
paths:
  /example:
    get:
      summary: Retrieve an example resource
      responses:
        '200':
          description: Successful response
