[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["graphql_service_sample_1"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "graphql_service_sample_1"
  org = "kajendranalagaratnam"
  version = "3.1.2"

