[package]
org = "KajendranAlagaratnam"
name = "gql_component"
version = "1.0.0"
export = ["gql_component"]
distribution = "2201.3.1"
keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
icon = "docs/icon.png"

[build-options]
observabilityIncluded = true
